// Shared by the browser and API. Cloud dashboards contain replay settings,
// never cached answers. Unknown properties are omitted at every object level.
const scalar = 'scalar';
const fields = keys => Object.fromEntries(keys.split(' ').map(key => [key, scalar]));
const list = schema => ({ list: schema });
const map = schema => ({ map: schema });
const value = 'value';
const filter = {
    ...fields('column field operator op pattern negate isHaving includeNonPositive multiplier compositeRef'),
    value, values: list(scalar),
    grounding: fields('kind table column confidence'),
};
const formatting = {
    ...fields('colorMode numberFormat fontSize headerSize headerBold headerColor showLabels showDataLabels dataLabelMode dataLabelSize dataLabelBold dataLabelColor movingAvgWindow decimals dateFormat axisBold axisColor axisLabelSize mapLabelContent showAxis showXAxis showYAxis yAxisFormat showGridLines _legibilityUpgraded'),
    tableCalculations: list(scalar),
    tableCalculationComparison: fields('mode referenceValue'),
};
const query = {
    ...fields('metric dimension aggregation timeGrain analysisType limit sort chartType questionLabel asOfDate includeZeroValues comparison comparisonMode comparisonGrain comparisonOffset chartStyle axisMode questionId timeFilter aiSql'),
    filters: map(list(scalar)), excludeFilters: map(list(scalar)),
    measureFilters: list(filter), numericFilters: list(filter), likeFilters: list(filter),
    dateFilters: list({ ...fields('column timeGrain'), values: list(scalar) }),
    numericRanges: list(fields('column min max')),
    aggregateFilters: list({ ...fields('column op compareAgg compareColumn multiplier includeNonPositive'), value }),
    distribution: fields('column bins'), groupAvgHaving: fields('op metricIndex'),
    secondaryMetrics: list(scalar), secondaryDimensions: list(scalar), tableCalculations: list(scalar),
    secondaryMetricAggregations: map(scalar), secondaryMetricVisuals: map(scalar), semanticRoles: map(scalar),
    alert: fields('enabled threshold operator color'),
    chart: fields('color colorMode showLabels showGrid type fontSize conditionalFormatting xAxisFormat yAxisFormat decimals'),
};
const plan = {
    ...fields('intent limit ambiguous clarificationQuestion resultGrain originalQuestion'),
    dimensions: list(fields('field timeGrain')),
    metrics: list(fields('field agg compositeId derivedMetricId')),
    filters: list(filter), sort: list(fields('field dir')),
    projectionFields: list(scalar), comparison: fields('type mode offset grain'),
};
const chart = {
    ...fields('chartType xKey yKey useDualAxis leftAxisFormat rightAxisFormat topN'),
    secondaryYKeys: list(scalar),
    // reason and growth are derived answers, not required to replay the query.
};
const result = {
    ...fields('xKey yKey yLabel sql calculatedSql vis axisMode visualizationMode'),
    config: query, queryConfig: query, formatting,
    secondaryYKeys: list(scalar),
    aiSqlRefresh: { ...fields('version source question sql'), plan, chart },
};
const item = {
    ...fields('id title width pinnedAt datasetId datasetName datasetVersion ignoreGlobalFilter'),
    result,
};
const layout = fields('i x y w h minW minH maxW maxH static isDraggable isResizable isBounded');
const dashboard = {
    ...fields('id name dataset_id created_at updated_at autoGenerated sourceDatasetId'),
    items: list(item), layout: list(layout),
    filters: list({ ...fields('column'), values: list(scalar) }), formatting,
};

function project(input, schema, depth = 0) {
    if (depth > 24 || input === undefined) return undefined;
    if (schema === scalar) {
        return input === null || ['string', 'boolean'].includes(typeof input)
            || (typeof input === 'number' && Number.isFinite(input)) ? input : undefined;
    }
    if (schema === value) {
        if (Array.isArray(input)) return input.map(v => project(v, scalar)).filter(v => v !== undefined);
        return project(input, scalar);
    }
    if (input === null) return null;
    if (schema.list) return Array.isArray(input)
        ? input.map(v => project(v, schema.list, depth + 1)).filter(v => v !== undefined) : undefined;
    if (!input || typeof input !== 'object' || Array.isArray(input)) return undefined;
    const output = {};
    for (const [key, childSchema] of Object.entries(schema.map
        ? Object.fromEntries(Object.keys(input).map(key => [key, schema.map])) : schema)) {
        if (['__proto__', 'constructor', 'prototype'].includes(key)) continue;
        if (!Object.prototype.hasOwnProperty.call(input, key)) continue;
        const clean = project(input[key], childSchema, depth + 1);
        if (clean !== undefined) output[key] = clean;
    }
    return output;
}

/** Produces a fresh object; does not truncate or mutate locally cached results. */
export function sanitizeDashboard(input) {
    const clean = project(input, dashboard) || {};
    clean.items = (clean.items || []).filter(i => i && i.id && i.result).map(i => ({
        ...i,
        result: { ...i.result, data: [], insight: '', needsLocalData: true },
    }));
    return clean;
}

/** Compare only the replay recipe, not formatting or data-dependent outputs. */
export function dashboardRecipeKey(item) {
    const clean = project(item, {
        datasetId: scalar, datasetVersion: scalar,
        result: {
            xKey: scalar, yKey: scalar, sql: scalar, calculatedSql: scalar, secondaryYKeys: list(scalar),
            config: query, queryConfig: query, aiSqlRefresh: { sql: scalar, plan, chart },
        },
    });
    return JSON.stringify(clean);
}
