/**
 * Deterministic parameter catalog — the admin-facing map of how AI SQL answers a
 * question. Two deterministic tiers, then the genuine remainder:
 *
 *   1. Question Builder base engine  — mapped by qbMapper, compiled by compileSQL.
 *   2. Deterministic correction engine — correctSQL builds the SQL for comparison,
 *      growth, trend enrichment and two-stage derived metrics. The LLM produces
 *      the PLAN (intent) but never writes this SQL.
 *   3. LLM-written SQL — only for shapes neither deterministic engine covers
 *      (relational set logic), or as a last-resort repair when they error.
 *
 * "Deterministic" here means the SQL is generated by rules, not by the LLM.
 * Every path still uses the LLM once, to turn the question into a plan.
 *
 * This mirrors services/ai-sql/qbMapper.ts + sqlCorrectionEngine.ts — keep it in
 * sync when you add a knob so the Parameters page stays truthful.
 */

export interface KnobDoc {
    name: string;
    example: string;
    sqlShape: string;
    group: 'Aggregation' | 'Group-by' | 'Filter' | 'Shape' | 'Ordering';
}

export interface CorrectionDoc {
    name: string;
    example: string;
    sqlShape: string;
}

export interface FallbackDoc {
    name: string;
    example: string;
    reason: string;
}

/** Tier 1 — the deterministic Question Builder base engine. */
export const DETERMINISTIC_KNOBS: KnobDoc[] = [
    { group: 'Aggregation', name: 'Sum / Average / Min / Max', example: 'What is the total revenue?', sqlShape: 'SELECT SUM(total_price) FROM data' },
    { group: 'Aggregation', name: 'Median', example: 'What is the median order value?', sqlShape: 'SELECT MEDIAN(total_price) FROM data' },
    { group: 'Aggregation', name: 'Count', example: 'How many orders are there?', sqlShape: 'SELECT COUNT(*) FROM data' },
    { group: 'Aggregation', name: 'Count distinct', example: 'How many distinct customers ordered?', sqlShape: 'SELECT COUNT(DISTINCT customer_id) FROM data' },
    { group: 'Aggregation', name: 'Multiple metrics / correlation', example: 'Revenue vs quantity by category', sqlShape: 'SELECT category, SUM(total_price), SUM(quantity) … GROUP BY category' },

    { group: 'Group-by', name: 'By category (dimension)', example: 'Revenue by channel', sqlShape: 'SELECT channel, SUM(total_price) … GROUP BY channel' },
    { group: 'Group-by', name: 'By time grain', example: 'Revenue by month', sqlShape: "… GROUP BY DATE_TRUNC('month', order_date)" },
    { group: 'Group-by', name: 'Two dimensions', example: 'Revenue by channel and category', sqlShape: '… GROUP BY channel, category' },

    { group: 'Filter', name: 'Equals / in', example: 'Total revenue from Delivery orders', sqlShape: "WHERE channel IN ('Delivery')" },
    { group: 'Filter', name: 'Exclude (≠ / not in)', example: 'Revenue excluding Online orders', sqlShape: "WHERE channel NOT IN ('Online')" },
    { group: 'Filter', name: 'Text contains (LIKE)', example: 'Revenue for products containing "Pro"', sqlShape: "WHERE product LIKE '%Pro%'" },
    { group: 'Filter', name: 'Numeric compare / range', example: 'Orders over $15 / between $10 and $18', sqlShape: 'WHERE total_price > 15  ·  WHERE total_price BETWEEN 10 AND 18' },
    { group: 'Filter', name: 'Date range', example: 'Revenue between two dates', sqlShape: 'WHERE order_date::TIMESTAMP BETWEEN … AND …' },
    { group: 'Filter', name: 'Relative date', example: 'Revenue this month', sqlShape: 'WHERE order_date IN (this month)' },
    { group: 'Filter', name: 'Above / below average (rows)', example: 'How many orders are above the average order value?', sqlShape: 'WHERE total_price > (SELECT AVG(total_price) FROM data)' },
    { group: 'Filter', name: 'Above / below average (groups)', example: 'Customers billing above the average customer', sqlShape: 'HAVING SUM(x) > (SELECT AVG(g) FROM (SELECT SUM(x) g … GROUP BY …))' },
    { group: 'Filter', name: 'Post-aggregate threshold (HAVING)', example: 'Channels with revenue over 10,000', sqlShape: 'HAVING SUM(total_price) > 10000' },
    { group: 'Filter', name: 'Set / anti-join (has X but not Y)', example: 'Customers who bought Coffee but never Tea', sqlShape: 'WHERE product IN (X) AND entity NOT IN (SELECT entity … WHERE product IN (Y))' },

    { group: 'Shape', name: 'Top-N / ranking', example: 'Top 5 products by revenue', sqlShape: '… ORDER BY SUM(total_price) DESC LIMIT 5' },
    { group: 'Shape', name: 'Share of total', example: 'What share of revenue does each channel represent?', sqlShape: 'each group ÷ grand total × 100 (% of total)' },
    { group: 'Shape', name: 'Distribution / histogram', example: 'Distribution of order values', sqlShape: 'bin the value into 10 equal-width buckets, COUNT per bucket' },
    { group: 'Shape', name: 'Trend over time', example: 'Revenue by month over time', sqlShape: 'time bucket + growth / running total (post-SQL)' },

    { group: 'Ordering', name: 'Sort ascending / descending', example: 'Channels from highest to lowest revenue', sqlShape: 'ORDER BY … DESC' },
    { group: 'Ordering', name: 'Limit', example: 'Show the top 3', sqlShape: 'LIMIT 3' },
];

/** Tier 2 — deterministic SQL built by the correction engine (not the LLM). */
export const CORRECTION_ENGINE_SHAPES: CorrectionDoc[] = [
    { name: 'Period comparison', example: 'Revenue this month vs last month', sqlShape: 'current vs previous period, UNION ALL — built deterministically, growth computed post-SQL' },
    { name: 'Trend comparison', example: 'Revenue this year vs last year over time', sqlShape: 'two overlapping period series with LAG-style growth' },
    { name: 'Growth ranking', example: 'Which products are growing fastest?', sqlShape: 'per-entity period-over-period change, ranked' },
    { name: 'Contribution / mix-shift', example: 'What drove the change in revenue by channel?', sqlShape: 'per-segment current vs previous delta (FULL OUTER JOIN of two periods), ranked' },
    { name: 'Two-stage derived metric', example: 'Average daily sales', sqlShape: 'AVG(SUM(sales) GROUP BY day) — nested aggregation' },
];

/** Tier 3 — genuinely still LLM-written (or unsupported) SQL. */
export const AI_ROUTED_SHAPES: FallbackDoc[] = [
    { name: 'Raw two-variable scatter', example: 'Every order plotted as price vs quantity', reason: 'Row-level (non-aggregated) two-metric output; the builder is aggregation-oriented.' },
];

/** Correction-engine intents — used by the live demo to label deterministic
 *  shapes the QB base engine does not itself map. */
export const CORRECTION_ENGINE_INTENTS = new Set([
    'total_comparison', 'trend_comparison', 'growth_analysis', 'derived_metric',
]);

export const DETERMINISTIC_COUNT = DETERMINISTIC_KNOBS.length;
export const CORRECTION_COUNT = CORRECTION_ENGINE_SHAPES.length;
export const AI_ROUTED_COUNT = AI_ROUTED_SHAPES.length;
