// ═══════════════════════════════════════════════════════════════════
// DuckDB-WASM Engine — In-Browser Columnar SQL Execution
//
// This module provides a real SQL execution engine in the browser
// using DuckDB compiled to WebAssembly. It can execute the same SQL
// generated by sqlCompiler.ts against actual data loaded from CSV/Excel.
//
// Architecture:
// 1. Lazy-initialized singleton DuckDB instance
// 2. Data is loaded into DuckDB tables on demand
// 3. SQL from compileSQL/compileEnrichedSQL executes against real DuckDB
// 4. Results are returned in the same format as executeQueryPlan
//
// This transforms Astrabi from "generates SQL cosmetically" to
// "executes real SQL in a columnar engine — zero infrastructure."
// ═══════════════════════════════════════════════════════════════════

import * as duckdb from '@duckdb/duckdb-wasm';
import { logger } from './logger';
import { finiteOrNull } from '../utils/numberSafety';

/**
 * Normalise a DuckDB DATE/TIMESTAMP value to a display-ready string.
 *
 * DuckDB-WASM hands these back as epoch offsets (Date32 = days, Date64 /
 * TIMESTAMP = milliseconds, sometimes as BigInt) rather than dates. Returned
 * raw they render as "1,751,241,600,000" and are treated as a huge numeric
 * metric by the profiler and charts. Everything else in the app represents
 * dates as 'YYYY-MM-DD' strings, so match that. A timestamp carrying a real
 * time-of-day keeps it.
 */
export function epochToDateString(val: any): string | null {
    if (val === null || val === undefined) return null;
    if (typeof val === 'string') return val;               // already normalised

    let ms: number;
    if (val instanceof Date) {
        ms = val.getTime();
    } else {
        const n = typeof val === 'bigint' ? Number(val) : Number(val);
        if (!Number.isFinite(n)) return null;
        // Date32 stores DAYS since epoch; anything larger is milliseconds.
        // 1e6 days is ~year 4707, well beyond any real business date.
        ms = Math.abs(n) < 1e6 ? n * 86400000 : n;
    }

    if (!Number.isFinite(ms)) return null;
    const d = new Date(ms);
    if (isNaN(d.getTime())) return null;

    const iso = d.toISOString();
    // Midnight UTC → a plain date; otherwise keep the time component.
    return iso.endsWith('T00:00:00.000Z') ? iso.slice(0, 10) : iso.slice(0, 19).replace('T', ' ');
}

// ── Singleton State ──────────────────────────────────────────────

let db: duckdb.AsyncDuckDB | null = null;
let conn: duckdb.AsyncDuckDBConnection | null = null;
let initPromise: Promise<void> | null = null;
let initError: Error | null = null;
let initAttempts = 0;
const MAX_INIT_RETRIES = 3;
const loadedTables = new Map<string, Promise<void>>();

// ── Initialization ───────────────────────────────────────────────

/**
 * Initialize DuckDB-WASM with automatic retry and exponential backoff.
 * If initialization fails due to a transient error (network, WASM compilation),
 * it resets state and retries up to MAX_INIT_RETRIES times.
 */
async function initDuckDB(): Promise<void> {
    // DuckDB-WASM requires a browser Web Worker. In environments without one
    // (server-side rendering, unit tests, restricted sandboxes) there is no
    // point spinning through retries + exponential backoff against an
    // impossible environment — fail fast with a clear message so callers can
    // fall back to the pure-JS analysis path immediately.
    if (typeof Worker === 'undefined') {
        throw new Error('DuckDB-WASM unavailable: Web Worker is not supported in this environment');
    }
    // If we think we have a connection, verify it's still alive
    if (db && conn) {
        try {
            await conn.query('SELECT 1');
            return; // Connection is healthy
        } catch (_) {
            // Connection is stale (tab was asleep, WASM worker died, etc.)
            logger.info('[DuckDB]', 'Connection stale — resetting for re-initialization');
            db = null;
            conn = null;
            initPromise = null;
            initAttempts = 0;
            loadedTables.clear();
        }
    }
    if (initPromise) return initPromise;

    initPromise = (async () => {
        let lastError: Error | null = null;

        for (let attempt = initAttempts; attempt < MAX_INIT_RETRIES; attempt++) {
            try {
                initAttempts = attempt + 1;
                logger.info('[DuckDB]', `Initializing WASM engine (attempt ${attempt + 1}/${MAX_INIT_RETRIES})...`);
                const startTime = performance.now();

                // Use CDN bundles for simplicity — no Vite WASM config needed
                const JSDELIVR_BUNDLES = duckdb.getJsDelivrBundles();

                // Select a bundle based on browser capabilities
                const bundle = await duckdb.selectBundle(JSDELIVR_BUNDLES);

                const worker_url = URL.createObjectURL(
                    new Blob([`importScripts("${bundle.mainWorker!}");`], { type: 'text/javascript' })
                );

                const worker = new Worker(worker_url);
                const duckdbLogger = new duckdb.ConsoleLogger();
                db = new duckdb.AsyncDuckDB(duckdbLogger, worker);
                await db.instantiate(bundle.mainModule, bundle.pthreadWorker);

                conn = await db.connect();

                const elapsed = Math.round(performance.now() - startTime);
                logger.info('[DuckDB]', `WASM engine ready in ${elapsed}ms`);

                URL.revokeObjectURL(worker_url);

                // Success — reset error state
                initError = null;
                return;
            } catch (err) {
                lastError = err as Error;
                // Clean up partial state from failed attempt
                db = null;
                conn = null;

                logger.error('[DuckDB]', `Init attempt ${attempt + 1} failed:`, err);

                if (attempt < MAX_INIT_RETRIES - 1) {
                    // Exponential backoff: 1s, 2s, 4s
                    const delay = 1000 * Math.pow(2, attempt);
                    logger.info('[DuckDB]', `Retrying in ${delay}ms...`);
                    await new Promise(resolve => setTimeout(resolve, delay));
                }
            }
        }

        // All retries exhausted
        initError = lastError;
        initPromise = null;  // Reset so future calls can retry after resetDuckDB()
        throw lastError;
    })();

    return initPromise;
}

/**
 * Reset DuckDB state to allow re-initialization.
 * Call this when the user wants to retry after a failure,
 * or when the app detects the connection is broken.
 */
export function resetDuckDB(): void {
    db = null;
    conn = null;
    initPromise = null;
    initError = null;
    initAttempts = 0;
    loadedTables.clear();
    logger.info('[DuckDB]', 'State reset — next query will re-initialize');
}

// ── Table Management ─────────────────────────────────────────────

/**
 * Sanitize a table name for DuckDB (remove special chars, lowercase)
 */
function sanitizeTableName(name: string): string {
    return name
        .replace(/[^a-zA-Z0-9_]/g, '_')
        .replace(/^_+|_+$/g, '')
        .toLowerCase()
        || 'dataset';
}

/**
 * Load an array of row objects into a DuckDB table.
 * Infers column types from the data and uses INSERT statements.
 */
async function loadDataIntoTable(tableName: string, rows: any[]): Promise<void> {
    if (!conn || rows.length === 0) return;

    const safeName = sanitizeTableName(tableName);

    // If a load is already in flight for this table, await it and return
    if (loadedTables.has(safeName)) {
        await loadedTables.get(safeName);
        return;
    }

    // Start the actual load and register the promise so concurrent callers await it
    const loadPromise = (async () => {
        // Drop any existing table to ensure fresh data
        await conn!.query(`DROP TABLE IF EXISTS "${safeName}"`);

        // Infer schema from first row
        const sampleRow = rows[0];
        const columns = Object.keys(sampleRow);

        const colInfos = columns.map(col => {
            // Infer the column type by scanning ALL rows — NOT just the first 100.
            // A column can look numeric in the first rows but hold codes like
            // "00D5" further down (common in real datasets, e.g. BIRD's schools).
            // Sampling only the head types it DOUBLE and the INSERT then fails
            // ("Could not convert string '00D5' to DOUBLE"). We stop early the
            // moment we see a non-numeric, non-date value — that column is text.
            let hasDate = false;
            let hasNumber = false;
            let hasString = false;

            for (let i = 0; i < rows.length; i++) {
                const val = rows[i][col];
                if (val === null || val === undefined || val === '') continue;

                // A native JS number is unambiguously numeric.
                if (typeof val === 'number') { hasNumber = true; continue; }

                const strVal = String(val);
                // Check if it's a date
                if (/^\d{4}-\d{2}-\d{2}/.test(strVal) || /^\d{1,2}\/\d{1,2}\/\d{2,4}/.test(strVal)) {
                    hasDate = true;
                }
                // Check if it's a number
                else if (!isNaN(Number(strVal.replace(/[$,]/g, ''))) && strVal.trim() !== '') {
                    hasNumber = true;
                } else {
                    hasString = true;
                    break; // definitively text — no need to scan further
                }
            }

            // Priority: if any strings found, use VARCHAR; otherwise prefer number > date
            let sqlType = 'VARCHAR';
            if (!hasString && !hasDate && hasNumber) sqlType = 'DOUBLE';
            else if (!hasString && hasDate && !hasNumber) sqlType = 'VARCHAR'; // Keep dates as strings to match JS engine behavior

            return { col, sqlType };
        });

        const colDefs = colInfos.map(ci => `"${ci.col.replace(/"/g, '""')}" ${ci.sqlType}`);
        const colType = new Map(colInfos.map(ci => [ci.col, ci.sqlType]));

        // Create table
        const createSQL = `CREATE TABLE "${safeName}" (${colDefs.join(', ')})`;
        await conn!.query(createSQL);

        // Batch insert using prepared statements for performance
        // DuckDB-WASM supports inserting from Arrow, but for simplicity use SQL batches
        const BATCH_SIZE = 1000;
        for (let batchStart = 0; batchStart < rows.length; batchStart += BATCH_SIZE) {
            const batch = rows.slice(batchStart, batchStart + BATCH_SIZE);
            const valueRows = batch.map(row => {
                const vals = columns.map(col => {
                    const v = row[col];
                    if (v === null || v === undefined) return 'NULL';
                    const s = String(v).replace(/'/g, "''");
                    // Quote per the COLUMN type, not the value: a text column keeps
                    // codes/leading-zeros intact; a numeric column takes bare
                    // numbers (or NULL if a stray value isn't numeric).
                    if (colType.get(col) === 'DOUBLE') {
                        const cleaned = s.replace(/[$,]/g, '');
                        return (cleaned.trim() !== '' && !isNaN(Number(cleaned))) ? cleaned : 'NULL';
                    }
                    return `'${s}'`;
                });
                return `(${vals.join(', ')})`;
            });

            const insertSQL = `INSERT INTO "${safeName}" VALUES ${valueRows.join(', ')}`;
            await conn!.query(insertSQL);
        }

        logger.info('[DuckDB]', `Loaded ${rows.length} rows into table "${safeName}" (${columns.length} columns)`);
    })();

    loadedTables.set(safeName, loadPromise);

    try {
        await loadPromise;
    } catch (err) {
        // If loading fails, remove from map so it can be retried
        loadedTables.delete(safeName);
        throw err;
    }
}

// ── SQL Execution ────────────────────────────────────────────────

export interface DuckDBResult {
    success: boolean;
    data: any[];
    columns: string[];
    rowCount: number;
    executionTimeMs: number;
    error?: string;
}

/**
 * Execute a SQL query against DuckDB-WASM.
 * Requires the table to be loaded first via `loadDataIntoTable`.
 */
async function executeSQLQuery(sql: string): Promise<DuckDBResult> {
    if (!conn) {
        return {
            success: false, data: [], columns: [],
            rowCount: 0, executionTimeMs: 0,
            error: 'DuckDB connection not initialized'
        };
    }

    const startTime = performance.now();

    try {
        const result = await conn.query(sql);
        const executionTimeMs = Math.round(performance.now() - startTime);

        // Convert Arrow table to plain JS objects
        const columns = result.schema.fields.map(f => f.name);
        const data: any[] = [];

        // Columns DuckDB typed as DATE/TIMESTAMP come back as epoch numbers, not
        // dates. Left alone they render as "1,751,241,600,000" and get charted as
        // a giant metric. Normalise them to the same 'YYYY-MM-DD' strings the rest
        // of the app uses, so they read and chart as dates.
        const dateCols = new Set<string>();
        for (const f of result.schema.fields) {
            const t = String((f as any).type ?? '').toLowerCase();
            if (t.includes('date') || t.includes('timestamp')) dateCols.add(f.name);
        }

        for (let i = 0; i < result.numRows; i++) {
            const row: any = {};
            for (const col of columns) {
                const colData = result.getChild(col);
                if (colData) {
                    const val = colData.get(i);
                    if (dateCols.has(col)) {
                        row[col] = epochToDateString(val);
                    } else {
                        // Convert BigInt to number (DuckDB returns BigInt for integers).
                        // Guarantee finiteness at the SQL boundary: any inf/NaN that a
                        // division or aggregate could yield becomes null, never garbage.
                        row[col] = typeof val === 'bigint' ? Number(val) : finiteOrNull(val);
                    }
                } else {
                    row[col] = null;
                }
            }
            data.push(row);
        }

        logger.debug('[DuckDB]', `Query executed in ${executionTimeMs}ms, ${data.length} rows returned`);

        return {
            success: true,
            data,
            columns,
            rowCount: data.length,
            executionTimeMs,
        };
    } catch (err) {
        const executionTimeMs = Math.round(performance.now() - startTime);
        const errorMsg = err instanceof Error ? err.message : String(err);
        logger.error('[DuckDB]', `Query failed (${executionTimeMs}ms):`, errorMsg);

        return {
            success: false,
            data: [],
            columns: [],
            rowCount: 0,
            executionTimeMs,
            error: errorMsg,
        };
    }
}

// ── Public API ───────────────────────────────────────────────────

/**
 * Execute a QueryPlan via DuckDB-WASM.
 *
 * 1. Initializes DuckDB-WASM (lazy, singleton)
 * 2. Loads dataset rows into a DuckDB table
 * 3. Compiles the QueryPlan to SQL via sqlCompiler
 * 4. Executes the SQL against DuckDB
 * 5. Returns results in the same format as executeQueryPlan
 *
 * @param sql - Pre-compiled SQL string from compileSQL/compileEnrichedSQL
 * @param tableName - The source table name (must match plan.source)
 * @param rows - The raw dataset rows to load into DuckDB
 * @returns DuckDBResult with data, columns, timing info
 */
export async function executeViaDuckDB(
    sql: string,
    tableName: string,
    rows: any[]
): Promise<DuckDBResult> {
    try {
        // 1. Initialize DuckDB
        await initDuckDB();

        // 2. Load data into table
        const safeName = sanitizeTableName(tableName);
        if (!loadedTables.has(safeName)) {
            await loadDataIntoTable(tableName, rows);
        }

        // 3. Rewrite the SQL to use the sanitized table name
        // The SQL compiler may use sanitizeIdentifier(name) which strips dots but keeps spaces/case
        // e.g., "Amazon Retail Sales.xlsx" → "Amazon Retail Salesxlsx" in SQL
        // DuckDB uses sanitizeTableName → "amazon_retail_sales_xlsx"
        // We need to match BOTH the original name and the sanitized-identifier form
        const sanitizedIdForm = tableName.replace(/[^a-zA-Z0-9_ ]/g, ''); // mirrors sanitizeIdentifier
        let rewrittenSQL = sql;

        // Try replacing the sanitized-identifier form first (most common in compiled SQL)
        if (sanitizedIdForm !== tableName) {
            rewrittenSQL = rewrittenSQL.replace(
                new RegExp(`"${sanitizedIdForm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`, 'gi'),
                `"${safeName}"`
            );
        }

        // Also try replacing the original name (in case it wasn't sanitized)
        rewrittenSQL = rewrittenSQL.replace(
            new RegExp(`"${tableName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`, 'gi'),
            `"${safeName}"`
        );

        // 4. Execute
        return await executeSQLQuery(rewrittenSQL);
    } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        return {
            success: false,
            data: [],
            columns: [],
            rowCount: 0,
            executionTimeMs: 0,
            error: `DuckDB initialization failed: ${errorMsg}`,
        };
    }
}

/**
 * Check if DuckDB-WASM is available and initialized.
 */
export function isDuckDBReady(): boolean {
    return db !== null && conn !== null;
}

/**
 * Check if DuckDB-WASM failed to initialize.
 */
export function getDuckDBError(): string | null {
    return initError ? initError.message : null;
}

/**
 * Force reload a table (e.g., after data changes).
 */
export async function reloadTable(tableName: string, rows: any[]): Promise<void> {
    const safeName = sanitizeTableName(tableName);
    loadedTables.delete(safeName);
    await loadDataIntoTable(tableName, rows);
}

/**
 * Get DuckDB status for UI display.
 */
export function getDuckDBStatus(): {
    initialized: boolean;
    tablesLoaded: string[];
    error: string | null;
} {
    return {
        initialized: db !== null,
        tablesLoaded: Array.from(loadedTables.keys()),
        error: initError?.message || null,
    };
}

// ── Drop-in Replacement for AlaSQL executeSQL ────────────────────

/**
 * Result type matching the old sqlExecutor.ts interface.
 */
export interface SQLExecutionResult {
    data: any[];
    columns: string[];
    error?: string;
}

/**
 * Normalize AI-generated SQL for DuckDB compatibility.
 * DuckDB speaks standard PostgreSQL, so we need far fewer hacks than AlaSQL.
 * Main job: ensure table references use the correct name.
 */
export function normalizeSQLForDuckDB(sql: string): string {
    let normalized = sql;

    // 1. Normalize table names: various forms → "data" (unquoted)
    //    The AI prompt tells models to use "data" as the table name.
    normalized = normalized.replace(/FROM\s+["']?orders["']?/gi, 'FROM data');
    normalized = normalized.replace(/FROM\s+["']?data["']?/gi, 'FROM data');

    // 2. Remove square brackets around column names (SQL Server style) → double quotes
    normalized = normalized.replace(/\[(\w+)\]/g, '"$1"');

    // Public SQLite benchmarks and some connectors use MySQL-style
    // backticks. DuckDB expects standard double-quoted identifiers.
    normalized = normalized.replace(/`([^`]+)`/g, (_match, identifier: string) => `"${identifier.replace(/"/g, '""')}"`);

    // 3. Handle SQLite's STRFTIME → DuckDB's strftime (case matters in DuckDB)
    // DuckDB supports strftime natively, just ensure correct case
    normalized = normalized.replace(/\bSTRFTIME\b/gi, 'strftime');

    // 4. Handle SUBSTR → SUBSTRING (DuckDB prefers SUBSTRING)
    normalized = normalized.replace(/\bSUBSTR\s*\(/gi, 'SUBSTRING(');

    // 5. Handle || for string concat (DuckDB supports || natively — no change needed)

    // 6. Handle IFNULL → COALESCE (DuckDB uses standard COALESCE)
    normalized = normalized.replace(/\bIFNULL\s*\(/gi, 'COALESCE(');

    // 7. Handle JULIANDAY → epoch-based date diff
    // JULIANDAY(a) - JULIANDAY(b) → DATE_DIFF('day', b::DATE, a::DATE)
    // This is complex; skip for now — DuckDB has native DATE_DIFF

    // 8. Normalize DATETIME/DATE function calls with modifiers
    //    SQLite: DATETIME('2023-06-20', '-6 days') → DuckDB: DATE '2023-06-20' - INTERVAL 6 DAY
    normalized = normalizeDateExpressions(normalized);

    logger.debug('[DuckDB]', 'Normalized SQL:', normalized);
    return normalized;
}

/**
 * Pre-process SQLite DATETIME('literal', 'modifier') into DuckDB interval syntax.
 */
function normalizeDateExpressions(sql: string): string {
    return sql.replace(
        /(?:DATETIME|DATE)\s*\(\s*'([^']+)'(?:\s*,\s*'([^']+)')?\s*\)/gi,
        (match, dateStr, modifier) => {
            if (!modifier) return `'${dateStr}'`;
            try {
                // Parse modifier like '-6 days', '+1 month'
                const m = modifier.match(/^([+-]?\d+)\s+(day|days|month|months|year|years)$/i);
                if (m) {
                    const n = parseInt(m[1], 10);
                    const unit = m[2].toUpperCase().replace(/S$/, '');
                    const absN = Math.abs(n);
                    const op = n >= 0 ? '+' : '-';
                    if (dateStr.toLowerCase() === 'now') {
                        return `(CURRENT_DATE ${op} INTERVAL ${absN} ${unit})`;
                    }
                    return `(DATE '${dateStr}' ${op} INTERVAL ${absN} ${unit})`;
                }
                return match; // Can't parse modifier, leave as-is
            } catch {
                return match;
            }
        }
    );
}

/**
 * Generate dim_date rows for DuckDB (same logic as dimDateGenerator.ts).
 * Returns an array of calendar rows between minDate and maxDate.
 */
function generateDimDateRows(minDate: string, maxDate: string): any[] {
    const rows: any[] = [];
    const start = new Date(minDate + 'T00:00:00');
    const end = new Date(maxDate + 'T00:00:00');
    if (isNaN(start.getTime()) || isNaN(end.getTime())) return rows;

    const pad = (n: number) => n.toString().padStart(2, '0');
    const d = new Date(start);
    while (d <= end) {
        const y = d.getFullYear();
        const m = d.getMonth() + 1;
        const day = d.getDate();
        const q = Math.ceil(m / 3);
        const dow = d.getDay(); // 0=Sun
        const dateKey = `${y}-${pad(m)}-${pad(day)}`;

        rows.push({
            date_key: dateKey,
            year: y,
            quarter: q,
            month: m,
            day: day,
            day_of_week: dow,
            year_quarter: `${y}-Q${q}`,
            year_month: `${y}-${pad(m)}`,
            month_name: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m-1],
            day_name: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][dow],
            is_weekend: dow === 0 || dow === 6 ? 1 : 0,
        });
        d.setDate(d.getDate() + 1);
    }
    return rows;
}

/**
 * Drop-in async replacement for the old AlaSQL-based executeSQL().
 *
 * Same interface: takes (rows, sql, timeContext?) and returns {data, columns, error?}.
 * Uses DuckDB-WASM for execution — faster, stricter, and runs in a Web Worker.
 *
 * The data is loaded into a table called "data" (matching AI prompt conventions).
 * If timeContext is provided, a dim_date table is also registered.
 */
/**
 * Load the original, UNJOINED source tables under their own names, alongside the
 * flattened "data" table.
 *
 * A multi-sheet workbook is joined into one wide table for the rest of the app,
 * but that join can duplicate fact rows — so a SUM over it is inflated. Loading
 * the real tables lets AI SQL join only what a question needs, at the right
 * grain. "data" is never overwritten, so nothing that depends on it changes.
 */
export async function loadRelatedTables(tables: { name: string; rows: any[] }[]): Promise<string[]> {
    await initDuckDB();
    if (!conn) throw new Error('DuckDB connection not available');

    const loaded: string[] = [];
    for (const t of tables) {
        const safe = sanitizeTableName(t.name);
        if (safe === 'data' || safe === 'dim_date') continue;   // never shadow these
        if (!t.rows?.length) continue;
        if (loadedTables.has(safe)) { loaded.push(safe); continue; }
        try {
            await loadDataIntoTable(t.name, t.rows);
            loaded.push(safe);
        } catch (err) {
            logger.warn('[DuckDB]', `Could not load related table "${t.name}":`, err);
        }
    }
    if (loaded.length) logger.info('[DuckDB]', `Related tables available: ${loaded.join(', ')}`);
    return loaded;
}

export async function executeSQLViaDuckDB(
    rows: any[],
    sql: string,
    timeContext?: { minDate: string; maxDate: string; primaryDateColumn?: string },
    relatedTables?: { name: string; rows: any[] }[]
): Promise<SQLExecutionResult> {
    const attemptExecution = async (): Promise<SQLExecutionResult> => {
        // 1. Initialize DuckDB
        await initDuckDB();
        if (!conn) throw new Error('DuckDB connection not available');

        // 2. Load data into "data" table (the standard table name used by AI prompts)
        const tableName = 'data';
        if (!loadedTables.has(tableName)) {
            await loadDataIntoTable(tableName, rows);
        }

        // 3. Load dim_date if time context provided
        if (timeContext?.minDate && timeContext?.maxDate) {
            const dimDateName = 'dim_date';
            if (!loadedTables.has(dimDateName)) {
                const dimRows = generateDimDateRows(timeContext.minDate, timeContext.maxDate);
                if (dimRows.length > 0) {
                    await loadDataIntoTable(dimDateName, dimRows);
                    logger.info('[DuckDB]', `dim_date loaded: ${dimRows.length} rows (${timeContext.minDate} → ${timeContext.maxDate})`);
                }
            }
        }

        // 3b. Load the unjoined source tables, when the dataset has them, so a
        // query can reference them by name instead of the flattened join.
        if (relatedTables?.length) {
            await loadRelatedTables(relatedTables);
        }

        // 4. Normalize SQL for DuckDB
        const normalizedSQL = normalizeSQLForDuckDB(sql);

        // 5. Execute
        logger.debug('[DuckDB]', 'Original SQL:', sql);
        const result = await executeSQLQuery(normalizedSQL);

        if (!result.success) {
            logger.error('[DuckDB]', 'Query failed:', result.error);
            return { data: [], columns: [], error: result.error };
        }

        logger.debug('[DuckDB]', `Result: ${result.rowCount} rows, ${result.columns.length} columns`);
        return { data: result.data, columns: result.columns };
    };

    try {
        return await attemptExecution();
    } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);

        // If it's a connection/init error, reset and retry once
        const isConnectionError = errorMsg.includes('connection not available')
            || errorMsg.includes('initialization failed')
            || errorMsg.includes('WebAssembly')
            || errorMsg.includes('Network error');

        if (isConnectionError) {
            logger.warn('[DuckDB]', `Connection error detected, resetting and retrying: ${errorMsg}`);
            resetDuckDB();
            try {
                return await attemptExecution();
            } catch (retryErr) {
                const retryMsg = retryErr instanceof Error ? retryErr.message : String(retryErr);
                logger.error('[DuckDB]', 'Retry also failed:', retryMsg);
                return { data: [], columns: [], error: retryMsg };
            }
        }

        logger.error('[DuckDB]', 'executeSQLViaDuckDB error:', errorMsg);
        return { data: [], columns: [], error: errorMsg };
    }
}

/**
 * Pre-load DuckDB and a dataset table so the first query has zero cold-start.
 * Call this after ETL completes to warm up the engine.
 */
export async function preloadDuckDB(tableName: string, rows: any[]): Promise<void> {
    try {
        await initDuckDB();
        await loadDataIntoTable(tableName, rows);
        // Also pre-load as "data" (the AI SQL standard table name)
        if (tableName !== 'data') {
            await loadDataIntoTable('data', rows);
        }
        logger.info('[DuckDB]', `Pre-loaded: ${rows.length} rows into "${tableName}" + "data"`);
    } catch (err) {
        logger.warn('[DuckDB]', 'Pre-load failed (non-fatal):', err);
    }
}

/**
 * Force reload the "data" table with new rows.
 * Call this when the active dataset changes.
 */
export async function reloadDataTable(rows: any[]): Promise<void> {
    loadedTables.delete('data');
    loadedTables.delete('dim_date');
    await loadDataIntoTable('data', rows);
}

/**
 * Replace every table used by an isolated benchmark case without tearing down
 * the WASM engine. Research cases can reuse generic table names across
 * different source databases, so retaining any related table would contaminate
 * the next gold or candidate result.
 */
export async function reloadIsolatedBenchmarkData(rows: any[]): Promise<void> {
    await initDuckDB();
    if (!conn) throw new Error('DuckDB connection not available');
    const tables = Array.from(loadedTables.keys());
    for (const table of tables) {
        await conn.query(`DROP TABLE IF EXISTS "${table.replace(/"/g, '""')}"`);
    }
    loadedTables.clear();
    await loadDataIntoTable('data', rows);
}
