// ═══════════════════════════════════════════════════════════════════
// DuckDB-WASM Engine — In-Browser Columnar SQL Execution
//
// This module provides a real SQL execution engine in the browser
// using DuckDB compiled to WebAssembly. It can execute the same SQL
// generated by sqlCompiler.ts against actual data loaded from CSV/Excel.
//
// Architecture:
// 1. Lazy-initialized singleton DuckDB instance
// 2. Data is loaded into DuckDB tables on demand
// 3. SQL from compileSQL/compileEnrichedSQL executes against real DuckDB
// 4. Results are returned in the same format as executeQueryPlan
//
// This transforms Astrabi from "generates SQL cosmetically" to
// "executes real SQL in a columnar engine — zero infrastructure."
// ═══════════════════════════════════════════════════════════════════

import * as duckdb from '@duckdb/duckdb-wasm';

// ── Singleton State ──────────────────────────────────────────────

let db: duckdb.AsyncDuckDB | null = null;
let conn: duckdb.AsyncDuckDBConnection | null = null;
let initPromise: Promise<void> | null = null;
let initError: Error | null = null;
const loadedTables = new Set<string>();

// ── Initialization ───────────────────────────────────────────────

async function initDuckDB(): Promise<void> {
    if (db) return;
    if (initError) throw initError;
    if (initPromise) return initPromise;

    initPromise = (async () => {
        try {
            console.log('[DuckDB] Initializing WASM engine...');
            const startTime = performance.now();

            // Use CDN bundles for simplicity — no Vite WASM config needed
            const JSDELIVR_BUNDLES = duckdb.getJsDelivrBundles();

            // Select a bundle based on browser capabilities
            const bundle = await duckdb.selectBundle(JSDELIVR_BUNDLES);

            const worker_url = URL.createObjectURL(
                new Blob([`importScripts("${bundle.mainWorker!}");`], { type: 'text/javascript' })
            );

            const worker = new Worker(worker_url);
            const logger = new duckdb.ConsoleLogger();
            db = new duckdb.AsyncDuckDB(logger, worker);
            await db.instantiate(bundle.mainModule, bundle.pthreadWorker);

            conn = await db.connect();

            const elapsed = Math.round(performance.now() - startTime);
            console.log(`[DuckDB] WASM engine ready in ${elapsed}ms`);

            URL.revokeObjectURL(worker_url);
        } catch (err) {
            initError = err as Error;
            console.error('[DuckDB] Failed to initialize:', err);
            throw err;
        }
    })();

    return initPromise;
}

// ── Table Management ─────────────────────────────────────────────

/**
 * Sanitize a table name for DuckDB (remove special chars, lowercase)
 */
function sanitizeTableName(name: string): string {
    return name
        .replace(/[^a-zA-Z0-9_]/g, '_')
        .replace(/^_+|_+$/g, '')
        .toLowerCase()
        || 'dataset';
}

/**
 * Load an array of row objects into a DuckDB table.
 * Infers column types from the data and uses INSERT statements.
 */
async function loadDataIntoTable(tableName: string, rows: any[]): Promise<void> {
    if (!conn || rows.length === 0) return;

    const safeName = sanitizeTableName(tableName);

    // If table already loaded with this name, drop and recreate
    if (loadedTables.has(safeName)) {
        await conn.query(`DROP TABLE IF EXISTS "${safeName}"`);
        loadedTables.delete(safeName);
    }

    // Infer schema from first row
    const sampleRow = rows[0];
    const columns = Object.keys(sampleRow);

    const colDefs = columns.map(col => {
        // Sample up to 100 rows to infer type
        const sampleSize = Math.min(rows.length, 100);
        let hasDate = false;
        let hasNumber = false;
        let hasString = false;

        for (let i = 0; i < sampleSize; i++) {
            const val = rows[i][col];
            if (val === null || val === undefined || val === '') continue;
            const strVal = String(val);

            // Check if it's a date
            if (/^\d{4}-\d{2}-\d{2}/.test(strVal) || /^\d{1,2}\/\d{1,2}\/\d{2,4}/.test(strVal)) {
                hasDate = true;
            }
            // Check if it's a number
            else if (!isNaN(Number(strVal.replace(/[$,]/g, ''))) && strVal.trim() !== '') {
                hasNumber = true;
            } else {
                hasString = true;
            }
        }

        // Priority: if any strings found, use VARCHAR; otherwise prefer number > date
        let sqlType = 'VARCHAR';
        if (!hasString && !hasDate && hasNumber) sqlType = 'DOUBLE';
        else if (!hasString && hasDate && !hasNumber) sqlType = 'VARCHAR'; // Keep dates as strings to match JS engine behavior

        const safCol = `"${col.replace(/"/g, '""')}"`;
        return `${safCol} ${sqlType}`;
    });

    // Create table
    const createSQL = `CREATE TABLE "${safeName}" (${colDefs.join(', ')})`;
    await conn.query(createSQL);

    // Batch insert using prepared statements for performance
    // DuckDB-WASM supports inserting from Arrow, but for simplicity use SQL batches
    const BATCH_SIZE = 1000;
    for (let batchStart = 0; batchStart < rows.length; batchStart += BATCH_SIZE) {
        const batch = rows.slice(batchStart, batchStart + BATCH_SIZE);
        const valueRows = batch.map(row => {
            const vals = columns.map(col => {
                const v = row[col];
                if (v === null || v === undefined) return 'NULL';
                const s = String(v).replace(/'/g, "''");
                // Try to keep numbers as numbers
                const cleaned = s.replace(/[$,]/g, '');
                if (!isNaN(Number(cleaned)) && cleaned.trim() !== '') {
                    return cleaned;
                }
                return `'${s}'`;
            });
            return `(${vals.join(', ')})`;
        });

        const insertSQL = `INSERT INTO "${safeName}" VALUES ${valueRows.join(', ')}`;
        await conn.query(insertSQL);
    }

    loadedTables.add(safeName);
    console.log(`[DuckDB] Loaded ${rows.length} rows into table "${safeName}" (${columns.length} columns)`);
}

// ── SQL Execution ────────────────────────────────────────────────

export interface DuckDBResult {
    success: boolean;
    data: any[];
    columns: string[];
    rowCount: number;
    executionTimeMs: number;
    error?: string;
}

/**
 * Execute a SQL query against DuckDB-WASM.
 * Requires the table to be loaded first via `loadDataIntoTable`.
 */
async function executeSQLQuery(sql: string): Promise<DuckDBResult> {
    if (!conn) {
        return {
            success: false, data: [], columns: [],
            rowCount: 0, executionTimeMs: 0,
            error: 'DuckDB connection not initialized'
        };
    }

    const startTime = performance.now();

    try {
        const result = await conn.query(sql);
        const executionTimeMs = Math.round(performance.now() - startTime);

        // Convert Arrow table to plain JS objects
        const columns = result.schema.fields.map(f => f.name);
        const data: any[] = [];

        for (let i = 0; i < result.numRows; i++) {
            const row: any = {};
            for (const col of columns) {
                const colData = result.getChild(col);
                if (colData) {
                    const val = colData.get(i);
                    // Convert BigInt to number (DuckDB returns BigInt for integers)
                    row[col] = typeof val === 'bigint' ? Number(val) : val;
                } else {
                    row[col] = null;
                }
            }
            data.push(row);
        }

        console.log(`[DuckDB] Query executed in ${executionTimeMs}ms, ${data.length} rows returned`);

        return {
            success: true,
            data,
            columns,
            rowCount: data.length,
            executionTimeMs,
        };
    } catch (err) {
        const executionTimeMs = Math.round(performance.now() - startTime);
        const errorMsg = err instanceof Error ? err.message : String(err);
        console.error(`[DuckDB] Query failed (${executionTimeMs}ms):`, errorMsg);

        return {
            success: false,
            data: [],
            columns: [],
            rowCount: 0,
            executionTimeMs,
            error: errorMsg,
        };
    }
}

// ── Public API ───────────────────────────────────────────────────

/**
 * Execute a QueryPlan via DuckDB-WASM.
 *
 * 1. Initializes DuckDB-WASM (lazy, singleton)
 * 2. Loads dataset rows into a DuckDB table
 * 3. Compiles the QueryPlan to SQL via sqlCompiler
 * 4. Executes the SQL against DuckDB
 * 5. Returns results in the same format as executeQueryPlan
 *
 * @param sql - Pre-compiled SQL string from compileSQL/compileEnrichedSQL
 * @param tableName - The source table name (must match plan.source)
 * @param rows - The raw dataset rows to load into DuckDB
 * @returns DuckDBResult with data, columns, timing info
 */
export async function executeViaDuckDB(
    sql: string,
    tableName: string,
    rows: any[]
): Promise<DuckDBResult> {
    try {
        // 1. Initialize DuckDB
        await initDuckDB();

        // 2. Load data into table
        const safeName = sanitizeTableName(tableName);
        if (!loadedTables.has(safeName)) {
            await loadDataIntoTable(tableName, rows);
        }

        // 3. Rewrite the SQL to use the sanitized table name
        // The SQL compiler uses the original dataset name, so we need to replace it
        const rewrittenSQL = sql.replace(
            new RegExp(`"${tableName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`, 'g'),
            `"${safeName}"`
        );

        // 4. Execute
        return await executeSQLQuery(rewrittenSQL);
    } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        return {
            success: false,
            data: [],
            columns: [],
            rowCount: 0,
            executionTimeMs: 0,
            error: `DuckDB initialization failed: ${errorMsg}`,
        };
    }
}

/**
 * Check if DuckDB-WASM is available and initialized.
 */
export function isDuckDBReady(): boolean {
    return db !== null && conn !== null;
}

/**
 * Check if DuckDB-WASM failed to initialize.
 */
export function getDuckDBError(): string | null {
    return initError ? initError.message : null;
}

/**
 * Force reload a table (e.g., after data changes).
 */
export async function reloadTable(tableName: string, rows: any[]): Promise<void> {
    const safeName = sanitizeTableName(tableName);
    loadedTables.delete(safeName);
    await loadDataIntoTable(tableName, rows);
}

/**
 * Get DuckDB status for UI display.
 */
export function getDuckDBStatus(): {
    initialized: boolean;
    tablesLoaded: string[];
    error: string | null;
} {
    return {
        initialized: db !== null,
        tablesLoaded: Array.from(loadedTables),
        error: initError?.message || null,
    };
}
