/**
 * Study 1 — the accuracy head-to-head, run for real.
 *
 * Two things are established here:
 *  A. THE HYBRID ARM, end-to-end: every question's plan is compiled by the real
 *     deterministic engine (correctSQL) and executed in DuckDB; the answer is
 *     graded against the independent JS oracle. Expectation: 100% correct, ZERO
 *     silent errors. This is a real, reportable result.
 *  B. THE INSTRUMENT IS VALID: the grader is fed synthetic SQL exhibiting each
 *     silent-error class and must classify each correctly (and must NOT flag a
 *     correct answer). Without this, the naive arm's future numbers wouldn't be
 *     trustworthy.
 *
 * The naive arm (an LLM writing SQL directly) needs an API key; when present it
 * runs and is written into the report, otherwise it's reported as "not run".
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import { createDuck, DuckHandle } from './helpers/duckdbNode';
import { runETLPipeline } from '../services/etlPipeline';
import { buildSemanticModel } from '../services/ai-sql/semanticLayer';
import { correctSQL } from '../services/ai-sql/sqlCorrectionEngine';
import { normalizeSQLForDuckDB } from '../services/duckdbEngine';
import { buildOrders, QUESTIONS, SCHEMA, OrderRow } from '../research/accuracyStudy/bank';
import { grade } from '../research/accuracyStudy/taxonomy';
import { runHybridArm, runNaiveArm, tally, formatReport } from '../research/accuracyStudy/runStudy';
import { getNaiveAdapter } from '../research/accuracyStudy/naiveAdapter';

let duck: DuckHandle, model: any, rows: OrderRow[];
beforeAll(async () => {
    duck = await createDuck();
    const etl = runETLPipeline(buildOrders(), 'orders.csv');
    rows = etl.rows as OrderRow[];
    model = buildSemanticModel({ id: 't', name: 'orders', rows, columns: etl.columns, totalRows: rows.length, etlLogs: [], timeContext: etl.timeContext } as any);
    duck.loadTable('data', rows);
}, 60000);
afterAll(() => duck?.close());

const compile = (plan: any) => normalizeSQLForDuckDB(correctSQL(plan, model));
const exec = (sql: string) => duck.query(sql);

// ─────────────────────────────────────────────────────────────────────
// A. The hybrid arm, for real.
// ─────────────────────────────────────────────────────────────────────
describe('Study 1 · Hybrid arm (plan → deterministic SQL → DuckDB)', () => {
    it('answers every question correctly with zero silent errors', async () => {
        const results = runHybridArm(rows, compile, exec);
        const t = tally(results);

        // Print per-question outcome for the record.
        for (const r of results) {
            console.log(`  ${r.grade.verdict === 'correct' ? '✓' : '✗'} ${r.id}: ${r.grade.verdict}${r.grade.errorClass ? ' (' + r.grade.errorClass + ')' : ''}`);
        }

        expect(t.queryFailed, 'no query should fail').toBe(0);
        expect(t.silentErrors, 'zero silent errors').toBe(0);
        expect(t.correct, 'all correct').toBe(QUESTIONS.length);

        // Emit the naive arm too if a key is configured, then write the report.
        const naiveAdapter = getNaiveAdapter();
        let naiveT;
        if (naiveAdapter) {
            const naiveResults = await runNaiveArm(rows, naiveAdapter, exec);
            naiveT = tally(naiveResults);
        }
        const report = formatReport(t, naiveT);
        console.log('\n' + report + '\n');
        try {
            mkdirSync('docs/research', { recursive: true });
            writeFileSync('docs/research/STUDY1_results.generated.md',
                `# Study 1 — generated results\n\n_Auto-generated by \`__tests__/accuracyStudy.test.ts\`. Dataset: ${rows.length} synthetic orders, ${QUESTIONS.length} questions._\n\n${report}\n`);
        } catch { /* fs may be sandboxed; the console output is the record */ }
    }, 120000);
});

// ─────────────────────────────────────────────────────────────────────
// B. The grader is a valid instrument — it catches each silent-error class
//    and never flags a correct answer.
// ─────────────────────────────────────────────────────────────────────
describe('Study 1 · Grader validity (the measuring instrument)', () => {
    const truthTotalRevenue = () => buildOrders().reduce((a, r) => a + r.revenue, 0);

    it('flags a DROPPED FILTER (counted everyone)', () => {
        const g = grade(
            { sql: 'SELECT COUNT(*) FROM data', answer: 600 },
            42, // true completed-count is far smaller
            { schema: SCHEMA, requiredFilterCols: ['status'] });
        expect(g.verdict).toBe('silent_error');
        expect(g.errorClass).toBe('dropped_filter');
    });

    it('flags a NON-ADDITIVE SUM (summed a rating)', () => {
        const g = grade(
            { sql: 'SELECT SUM("satisfaction_rating") FROM data', answer: 1800 },
            3.0,
            { schema: SCHEMA, metricCol: 'satisfaction_rating', requiredAgg: 'avg', nonAdditiveCols: ['satisfaction_rating'] });
        expect(g.verdict).toBe('silent_error');
        expect(g.errorClass).toBe('non_additive_sum');
    });

    it('flags an AGGREGATED IDENTIFIER (summed an id)', () => {
        const g = grade(
            { sql: 'SELECT SUM("order_id") FROM data', answer: 6_000_000 },
            truthTotalRevenue(),
            { schema: SCHEMA, idCols: ['order_id'] });
        expect(g.verdict).toBe('silent_error');
        expect(g.errorClass).toBe('aggregated_identifier');
    });

    it('flags a WRONG AGGREGATION (sum where avg was asked)', () => {
        const g = grade(
            { sql: 'SELECT SUM("revenue") FROM data', answer: truthTotalRevenue() },
            2000, // true average
            { schema: SCHEMA, metricCol: 'revenue', requiredAgg: 'avg' });
        expect(g.verdict).toBe('silent_error');
        expect(g.errorClass).toBe('wrong_aggregation');
    });

    it('flags IGNORED GROUPING (one number instead of a breakdown)', () => {
        const g = grade(
            { sql: 'SELECT SUM("revenue") FROM data', answer: truthTotalRevenue() },
            { North: 1, South: 2, East: 3, West: 4 },
            { schema: SCHEMA, requiredGroupByCols: ['region'] });
        expect(g.verdict).toBe('silent_error');
        expect(g.errorClass).toBe('ignored_grouping');
    });

    it('flags a HALLUCINATED FIELD (column not in schema)', () => {
        const g = grade(
            { sql: 'SELECT SUM("profit") FROM data', answer: 999 },
            truthTotalRevenue(),
            { schema: SCHEMA, metricCol: 'revenue', requiredAgg: 'sum' });
        expect(g.verdict).toBe('silent_error');
        expect(g.errorClass).toBe('hallucinated_field');
    });

    it('NEVER flags a correct answer as an error, however it was written', () => {
        const g = grade(
            { sql: 'SELECT SUM(revenue) AS x FROM data', answer: truthTotalRevenue() },
            truthTotalRevenue(),
            { schema: SCHEMA, metricCol: 'revenue', requiredAgg: 'sum' });
        expect(g.verdict).toBe('correct');
    });

    it('counts a plain wrong number with no known pattern as wrong_value, not a silent error', () => {
        const g = grade(
            { sql: 'SELECT SUM(revenue) FROM data WHERE region = \'Northh\'', answer: 0 },
            12345,
            { schema: SCHEMA, metricCol: 'revenue', requiredAgg: 'sum' });
        expect(g.verdict).toBe('wrong_value');
    });
});
